### PR TITLE
add gpt-4-1106-preview model

### PR DESCRIPTION
**Pull request by gschurck**

### CODE REVIEW

**Comment by lansgt** [comment]
+1 for this 🙏

**Comment by jmelovich** [comment]
+1

**Comment by zokovi** [comment]
+1

**Comment by leo852** [comment]
+1

**Comment by Vaalley** [comment]
Oops, didn't see your commit so I also made that same commit :') Oh well, good job!

**Comment by HrBingR** [comment]
+1, the only thing keeping me away from using this.

**Review by Supernova3339 — APPROVED** [review]
Functionality works, PR approved! We will merge this with the next release!

**Pull request merged**
